# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotfilesInstaller < Formula
  desc "Clones a github repo and creates symbolic links"
  homepage "https://github.com/Mephisto-Grumpy/dotfiles-installer"
  url "https://github.com/Mephisto-Grumpy/dotfiles-installer/archive/1.1.1.tar.gz"
  sha256 "30269721133c7b3ed23b9ea906806218d29afa881bf12f1a73b5ea7f13b1d208"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    if OS.mac?
      url "https://github.com/Mephisto-Grumpy/dotfiles-installer/releases/download/1.1.1/dotfiles-installer-darwin-amd64"
      sha256 ""
      bin.install "dotfiles-installer-darwin-amd64" => "dotfiles-installer"
    else
      url "https://github.com/Mephisto-Grumpy/dotfiles-installer/releases/download/1.1.1/dotfiles-installer-linux-amd64"
      sha256 ""
      bin.install "dotfiles-installer-linux-amd64" => "dotfiles-installer"
    end
  end

  test do
    assert_match "Version:", shell_output("#{bin}/dotfiles-installer --version")
  end
end
