# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotfilesInstaller < Formula
  desc "Clones a github repo and creates symbolic links"
  homepage "https://github.com/Mephisto-Grumpy/dotfiles-installer"
  url "https://github.com/Mephisto-Grumpy/dotfiles-installer/archive/release-12.tar.gz"
  sha256 "73895fd486f90957748c669cfd9556b507653509b9f5f217ac9d24d1ce45a532"
  license "MIT"

  def install
    bin.install "dotfiles-installer"
  end
end
